language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - master

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
